name: CI Playwright BDD

on:
  push:              # Lance la CI à chaque push
    branches: [ main, develop ]
  pull_request:      # Lance aussi sur les PR vers ces branches
    branches: [ main, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest   # Machine GitHub hébergée sous Linux

    steps:
      # 1) Récupérer le code du repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # Version de Node (adapte si besoin)
          cache: 'npm'         # Cache le dossier ~/.npm pour accélérer

      # 3) Installer les dépendances du projet
      - name: Install dependencies
        run: npm ci            # ou "npm install" si tu préfères

      # 4) Installer les navigateurs Playwright
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # 5) Lancer les tests BDD (Cucumber + Playwright)
      - name: Run BDD tests
        run: npm run test:bdd:html
        
     # 7) Uploader le rapport HTML Cucumber
      - name: Upload Cucumber HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: test-results/cuReports/html_report.html
          if-no-files-found: error      # si tu veux forcer l'erreur si le rapport manque
          retention-days: 30

      # 6) Générer le rapport Allure (si tu as un script npm prévu)
      - name: Generate Allure report
        if: always()           # s'exécute même si les tests échouent
        run: |
          npm run allure:generate || echo "No Allure generate script"

      # 7) Uploader le rapport Allure comme artefact
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          if-no-files-found: ignore

      # 8) Uploader les résultats Playwright (HTML report / traces)
      - name: Upload Playwright results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: |
            test-results/
            playwright-report/
          if-no-files-found: ignore
          retention-days: 30

